
export const ROUTES = {
  ROLE_SELECTION: 'ROLE_SELECTION',
  DISCOVERY: 'DISCOVERY',
  TRACKER: 'TRACKER',
  NETWORK: 'NETWORK',
  AGENT: 'AGENT',
  FOUNDER_HUB: 'FOUNDER_HUB',
  SP_ACTIVITY: 'SP_ACTIVITY',
  PROPOSAL_BUILDER: 'PROPOSAL_BUILDER'
} as const;
export type AppRoute = typeof ROUTES[keyof typeof ROUTES];
